---
resource_group_name: "{{ resource_group_name | default('openenv-d8ghz') }}"
region: "{{ region | default('eastus') }}"
vnet_cidr: "{{ vnet_cidr | default('10.0.0.0/16') }}"
subnet_cidr: "{{ subnet_cidr | default('10.0.0.0/24') }}"
vnet_name: "{{ vnet_name | default('controller-vnet') }}"
subnet_name: "{{ subnet_name | default('default') }}"
network_sec_group_name: "{{ network_sec_group_name | default('controler-nsg') }}"
rhel_vm_name: "{{ rhel_vm_name | default('RHEL-ansible') }}"
rhel_vm_size: "{{ rhel_vm_size | default('Standard_B2as_v2') }}"
rhel_vm_sku: "{{ rhel_vm_sku | default('ntg_rhel_8_2') }}"
rhel_public_ip_name: "{{ rhel_public_ip_name | default('rhel_demo_ip') }}"
rhel_nic_name: "{{ rhel_nic_name | default('rhel_demo_nic') }}"
rhel_admin_user: "{{ rhel_admin_user | default('ansible') }}"
rhel_admin_password: "{{ rhel_admin_password | default('RedHatAnsible123!') }}"
survey_public_ip: "{{ survey_public_ip | default('True') }}"
