- name: GitHub Deploy Git Hook Rules
  hosts: all
  sources:
    - ansible.eda.azure_service_bus:
        conn_str: "{{conn_str}}"
        queue_name: "{{queue}}"
  rules:
    - name: print output
      condition: event.output is defined
      action:
        print_event:
          var_root: output
    - name: debug
      enabled: False
      condition: event.payload is defined
      action:
        debug:
