---
- name: Create Azure VM
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    resource_group_name: openenv-d8ghz
    region: eastus
    vnet_cidr: '10.0.0.0/16'
    subnet_cidr: '10.0.0.0/24'
    vnet_name: 'controller-vnet'
    subnet_name: 'default'
    network_sec_group_name: 'controler-nsg'
    vm_name: 'eda'
    vm_size: 'Standard_B2as_v2'
    vm_sku: 'ntg_rhel_8_2'
    public_ip_name: "{{ vm_name }}_public_ip"
    nic_name: 'demo_nic'
    admin_user: 'ansible'
    admin_password: 'Passw0rd!'
    survey_public_ip: 'True'
  tasks:

    - name: Create public IP address
      azure.azcollection.azure_rm_publicipaddress:
        resource_group: "{{ resource_group_name }}"
        allocation_method: Static
        name: "{{ public_ip_name }}"
      register: output_ip_address
      #when: survey_public_ip == "True"

    - name: Dump public IP for VM which will be created
      debug:
        msg: "The public IP is {{ output_ip_address.state.ip_address }}"
      #when: survey_public_ip == "True"

    - name: Set Stat for Ansible Controller
      set_stats:
        data:
          azure_vm_public_ip: "{{ output_ip_address.state.ip_address }}"
        per_host: false
      #when: survey_public_ip == "True"

    - name: Create Network Security Group that allows SSH and RDP
      azure.azcollection.azure_rm_securitygroup:
        resource_group: "{{ resource_group_name }}"
        name: "{{ network_sec_group_name }}"
        rules:
          - name: SSH
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 1001
            direction: Inbound
          - name: RDP
            protocol: Tcp
            destination_port_range: 3389
            access: Allow
            priority: 1002
            direction: Inbound
          - name: http
            protocol: Tcp
            destination_port_range: 80
            access: Allow
            priority: 1003
            direction: Inbound

#    - name: Create virtual network interface card
#      azure.azcollection.azure_rm_networkinterface:
#        resource_group: "{{ resource_group_name }}"
#        name: "{{ nic_name }}"
#        virtual_network: "{{ vnet_name }}"
#        subnet: "{{ subnet_name }}"
#        security_group: "{{ network_sec_group_name }}"
#      when: survey_public_ip != "True"

    - name: Create virtual network interface card
      azure.azcollection.azure_rm_networkinterface:
        resource_group: "{{ resource_group_name }}"
        name: "{{ nic_name }}"
        virtual_network: "{{ vnet_name }}"
        subnet: "{{ subnet_name }}"
        public_ip_name: "{{ public_ip_name }}"
        security_group: "{{ network_sec_group_name }}"
      when: survey_public_ip == "True"

    - name: Create VM
      azure.azcollection.azure_rm_virtualmachine:
        resource_group: "{{ resource_group_name }}"
        name: "{{ vm_name }}"
        managed_disk_type: "Standard_LRS"
        vm_size: "{{ vm_size }}"
        admin_username: "{{ admin_user | default('ansible') }}"
        admin_password: "{{ admin_password }}"
        network_interfaces: "{{ nic_name }}"
        state: present
        started: true
        ssh_password_enabled: true
        ssh_public_keys:
          - path: /home/ansible/.ssh/authorized_keys
            key_data: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCffwOMWCjomX/ERSmbiFq6+i8gNL+A4sXB5vKqD1yCp6AEqsCD42Ag7x1NJ1i8hoPoebZxgWHI8PB0vih4tM0HnI3EKFNM6mKfb7Yue4su5ff/X81wcpVvt3Lk7CjGg16zZ0CQdn48zjmQK/NOosP0hzzoznnx8J/ClF2AauJanJQkoJsG7z9VDe0wqrZeDFb3r1Zx98npFGYJEwjSE9/LikAdVs9Ke8Z2kv1t/AwpO36VoHluz4j9VsqkO4sdKg1rPAu1IeKlqZXHCEFS49ZbWv3WbInvOtT1IbJk0iqGTWHY+2RGS1wFswzFPLfWG3YQFbwIwhyOGhZmxClQgBjKpY+NUleHXtwE3+T59+mBgGtzyMmmACZcBQG1JyXjA/FEkqR188CKFuOvEdlsI4zs0bcfQCWIHBNwmjX6bA39uozsNbn/bgZyC7KXk+2bmAaq6hn2cEsZUD+oDSVS0lcIW+GWIMuHFnjAQOvKYni2t7cIkKiciJ8bH5bwGt1aVnM="
        tags:
          "name": "{{ vm_name }}"
          "demo": "true"
          "os": "linux"
          "username": "{{ admin_user }}"
        image:
          offer: ntg_rhel_8_2
          publisher: ntegralinc1586961136942
          sku: "{{ vm_sku | default('ntg_rhel_8_2') }}"
          version: latest
        security_profile:
          security_type: Standard
