---
- name: Create Azure VM
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    resource_group_name: "{{ resource_group_name | default('openenv-d8ghz') }}"
    region: "{{ region | default('eastus') }}"
    vnet_cidr: "{{ vnet_cidr | default('10.0.0.0/16') }}"
    subnet_cidr: "{{ subnet_cidr | default('10.0.0.0/24') }}"
    vnet_name: "{{ vnet_name | default('controller-vnet') }}"
    subnet_name: "{{ subnet_name | default('default') }}"
    network_sec_group_name: "{{ network_sec_group_name | default('controler-nsg') }}"
    rhel_vm_name: "{{ rhel_vm_name | default('RHEL-ansible') }}"
    rhel_vm_size: "{{ rhel_vm_size | default('Standard_B2as_v2') }}"
    rhel_vm_sku: "{{ rhel_vm_sku | default('ntg_rhel_8_2') }}"
    rhel_public_ip_name: "{{ rhel_public_ip_name | default('rhel_demo_ip') }}"
    rhel_nic_name: "{{ rhel_nic_name | default('rhel_demo_nic') }}"
    rhel_admin_user: "{{ rhel_admin_user | default('ansible') }}"
    rhel_admin_password: "{{ rhel_admin_password | default('RedHatAnsible123!') }}"
    survey_public_ip: "{{ survey_public_ip | default('True') }}"
  tasks:

    - name: Create public IP address
      azure.azcollection.azure_rm_publicipaddress:
        resource_group: "{{ resource_group_name }}"
        allocation_method: Static
        name: "{{ rhel_public_ip_name }}"
      register: output_ip_address
      when: survey_public_ip == "True"

    - name: Dump public IP for VM which will be created
      debug:
        msg: "The public IP is {{ output_ip_address.state.ip_address }}"
      when: survey_public_ip == "True"

    - name: Set Stat for Ansible Controller
      set_stats:
        data:
          azure_vm_public_ip: "{{ output_ip_address.state.ip_address }}"
        per_host: false
      when: survey_public_ip == "True"

    - name: Create Network Security Group that allows SSH and RDP
      azure.azcollection.azure_rm_securitygroup:
        resource_group: "{{ resource_group_name }}"
        name: "{{ network_sec_group_name }}"
        rules:
          - name: SSH
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 1001
            direction: Inbound
          - name: RDP
            protocol: Tcp
            destination_port_range: 3389
            access: Allow
            priority: 1002
            direction: Inbound
          - name: http
            protocol: Tcp
            destination_port_range: 80
            access: Allow
            priority: 1003
            direction: Inbound

    - name: Create virtual network interface card
      azure.azcollection.azure_rm_networkinterface:
        resource_group: "{{ resource_group_name }}"
        name: "{{ rhel_nic_name }}"
        virtual_network: "{{ vnet_name }}"
        subnet: "{{ subnet_name }}"
        security_group: "{{ network_sec_group_name }}"
      when: survey_public_ip != "True"

    - name: Create virtual network interface card
      azure.azcollection.azure_rm_networkinterface:
        resource_group: "{{ resource_group_name }}"
        name: "{{ rhel_nic_name }}"
        virtual_network: "{{ vnet_name }}"
        subnet: "{{ subnet_name }}"
        public_ip_name: "{{ rhel_public_ip_name }}"
        security_group: "{{ network_sec_group_name }}"
      when: survey_public_ip == "True"

    - name: Create VM
      azure.azcollection.azure_rm_virtualmachine:
        resource_group: "{{ resource_group_name }}"
        name: "{{ rhel_vm_name }}"
        managed_disk_type: "Standard_LRS"
        vm_size: "{{ rhel_vm_size }}"
        admin_username: "{{ rhel_admin_user | default('ansible') }}"
        admin_password: "{{ rhel_admin_password }}"
        network_interfaces: "{{ rhel_nic_name }}"
        ssh_password_enabled: true
        tags:
          "name": "{{ rhel_vm_name }}"
          "demo": "true"
          "os": "linux"
          "username": "{{ rhel_admin_user }}"
        image:
          offer: ntg_rhel_8_2
          publisher: ntegralinc1586961136942
          sku: "{{ rhel_vm_sku | default('ntg_rhel_8_2') }}"
          version: latest
        security_profile:
          security_type: Standard
