---
- name: Create GCP resources and then create a GCP instance
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    gcp_project:  openenv-xqbbv
    gcp_zone: us-east1-b
    gcp_region: us-east1  
    vm_name: 'test'
    network_name: "{{ vm_name }}-gcp-network"
  tasks:
    - name: Create a disk mapped from a RHEL-8 image for rhel1
      google.cloud.gcp_compute_disk:
        name: "{{ vm_name }}"
        size_gb: 50
        source_image: "projects/rhel-cloud/global/images/rhel-8-v20231010"
        zone: "{{ gcp_zone }}"
        project: "{{ gcp_project }}"
        auth_kind: serviceaccount
        state: present
      register: diskrhel1

    - name: Create a Google Virtual Private Cloud (VPC) network
      google.cloud.gcp_compute_network:
        name: "{{ network_name }}"
        auto_create_subnetworks: 'false'
        project: "{{ gcp_project }}"
        auth_kind: serviceaccount
        state: present
      register: network

    - name: Create a subnetwork
      google.cloud.gcp_compute_subnetwork:
        name: instancenet
        region: us-east1
        network: "{{ network }}"
        ip_cidr_range: 172.16.0.0/16
        project: "{{ gcp_project }}"
        auth_kind: serviceaccount
        state: present
      register: vpcsubnet

    - name: Create a firewall rule to allow SSH
      google.cloud.gcp_compute_firewall:
        name: allowssh
        allowed:
          - ip_protocol: tcp
            ports:
              - '22'
              - '80'
              - '443'
        project: "{{ gcp_project }}"
        network: "{{ network }}"
        auth_kind: serviceaccount
        state: present
      register: sshallowed

    - name: Create an IPv4 public IP address for rhel1
      google.cloud.gcp_compute_address:
        name: rhel1ip
        region: "{{ gcp_region }}"
        project: "{{ gcp_project }}"
        auth_kind: serviceaccount
        state: present
      register: rhel1ip

    - name: Create the rhel1 VM instances
      google.cloud.gcp_compute_instance:
        name: rhel1
        machine_type: e2-standard-4
        disks:
          - auto_delete: 'true'
            boot: 'true'
            source: "{{ diskrhel1 }}"
          - auto_delete: 'true'
            interface: NVME
            type: SCRATCH
            initialize_params:
              disk_type: local-ssd
        labels:
          environment: production
        network_interfaces:
          - network: "{{ network }}"
            access_configs:
              - name: External NAT
                nat_ip: "{{ rhel1ip }}"
                type: ONE_TO_ONE_NAT
            subnetwork: "{{ vpcsubnet }}"
        zone: "{{ gcp_zone }}"
        project: "{{ gcp_project }}"
        auth_kind: serviceaccount
        state: present
